const discord = require("discord.js");
const request = require('node-superfetch');
const { Command } = require('discord.js-commando');

module.exports = class rufus extends Command {
  constructor(client) {
    super(client, {
      name: 'cat',
      group: 'misc',
      memberName: 'cat',
      aliases: ['randomcat'],
      description: 'Cats generated by AI',
      guildOnly: true,
      clientPermissions: ['ATTACH_FILES'],
      userPermissions: ['ATTACH_FILES'],
    });
  }

  async run(message) {
    const { body } = await request.get('https://thiscatdoesnotexist.com/');
    return message.channel.send('AI-Generated Cat', { files: [{ attachment: body, name: 'ai-artwork.jpg' }] });
  }
};